### ISSUE TITLE
Boost #nav-drawer links don't work

### ISSUE THREAD

**Issue by sharpchi** [gjb2048/moodle-format_grid#50]
In the Boost theme, the new #nav-drawer links don't allow the user to jump to the section in the grid-format.
![image](https://cloud.githubusercontent.com/assets/3774280/26053153/a9254d26-395f-11e7-8023-632d1c16ee4d.png)

**Comment by gjb2048** [comment]
What version of the Grid format?
What version of Moodle?
In what way don't work?  What do you expect them to do?
What is the behaviour in other themes such as Clean?
What is the value of the 'Course layout' course setting?

**Comment by sharpchi** [comment]
Grid format version: 2016111503
Moodle: 3.2.3 (2016120503.02)
The issue: The section links in the navdrawer menu in Boost theme, when using Grid format, don't open the grid pop-ups. They do not reload the page, which means the grid format doesn't automatically show the section pop-up on page load.

Other themes: The navdraw doesn't appear in Clean.

Course layout: Show all sections on one page (i.e. using #bookmarks rather than url parameters).

Since Boost is the default theme in Moodle 3.2 onwards, this should work.

**Comment by gjb2048** [comment]
Thanks, I'll review fully when I get a chance.  First glance is concern over duplication of functionality as might be existing methods to make this shorter.  Can it be made to work with the navigation block in other themes?

**Comment by sharpchi** [comment]
Any themes derived from Boost (and there seems to be a few now) this will work for. It could perhaps be extended to work with the "Section links" block or perhaps any link with a class you might want to define (e.g. gf_link), which I think might be your solution for #38.

The Navigation block in older themes have the section links as drop-down menu items, so I'm not sure it should work with those.

**Comment by gjb2048** [comment]
Going to leave as M3.2+

**Comment by petersercombe** [comment]
Hi all,

I think I'm experiencing an issue as a result of this - using Moodle 3.2.3+ Build: 20170622 with Grid format 3.2.1.3 and Boost theme. Course layout set to "show all sections on one page".

I'm finding that the other links in the nav drawer (Participants, Badges, Competencies and Grades) are opening a course section rather than their intended target.

E.g. Clicking "Badges"

![image](https://user-images.githubusercontent.com/16435816/27664709-6c4ddf06-5cac-11e7-9b8a-2937cd3eb5ce.png)

Opens Section 2:

![image](https://user-images.githubusercontent.com/16435816/27664725-86a6e87a-5cac-11e7-9f61-9909e0f33dc4.png)

Interestingly, it seems to be always section 2. Unsure if that's related to the fact that this particular course's id=2.

Links further down in the nav drawer are fine.

![image](https://user-images.githubusercontent.com/16435816/27664762-c02d9e18-5cac-11e7-8b17-67e733e21ebd.png)

**Comment by petersercombe** [comment]
With some more testing, I can confirm that rolling back the plugin to commit 94cff6a resolves the issue (but does remove the feature).

**Comment by gjb2048** [comment]
Cannot replicate even with a courseid of 2.  There is absolutely no way that https://github.com/gjb2048/moodle-format_grid/commit/94cff6a4f8769f66526faee5ef06e0d79362bf31 is the cause even if there was a bug for this.
