### ISSUE TITLE
convert_legacy_image is open to everyone

### ISSUE THREAD

**Issue by ewallah** [gjb2048/moodle-format_grid#93]
The file convert_legacy_image.php should be accessible for admins only, but it does not even check if a user is logged in or not.  As a result everybody on the internet (even a robot) can convert images just surfing to https://yoursite.org/course/format/grid/upgrade/convert_legacy_image.php.

**Comment by gjb2048** [comment]
?  What are you taking about with 'As a result everybody on the internet (even a robot) can convert images just surfing to' as the code takes no image related parameters!  -> https://github.com/gjb2048/moodle-format_grid/blob/master/upgrade/convert_legacy_image.php.  Therefore only 'if' there are legacy images in the database -> https://github.com/gjb2048/moodle-format_grid/blob/master/upgrade/convert_legacy_image.php#L122 - will anything actually happen and even then to images within Moodle and only 'within' Moodle.  But if you have evidence of how this is possible, then please do explain, I'm intrigued!

Since the code was created on the 4th November 2013, nobody has ever mentioned this before!

Clearly I need to now add a 'defined('MOODLE_INTERNAL') || die();' to prevent DB DOS as my knowledge has improved since then.

**Comment by ewallah** [comment]
require_login, require_capability and/or get_admins() will be needed too, otherwise guests and common users will be able to call the page and see results like https://capacitacion.ciat.org/course/format/grid/upgrade/convert_legacy_image.php

**Comment by gjb2048** [comment]
Ok, but I thought that a Robot could not discover the names of a PHP file on a server unless it was configured incorrectly to give out a file listing.

**Comment by gjb2048** [comment]
I'll think I'll just rename the file so it can't be executed, then add instructions at the top for the sysadmin to follow in the rare actuality that they need to run it.

**Comment by ewallah** [comment]
https://moodle.org/plugins/pluginversion.php?id=19632&smurf=html#phpcs warns twice about a missing login check and 4 times about a missing MOODLE_INTENAL, so it is not only the convert_legacy_image file that is revealing info.

**Comment by gjb2048** [comment]
Fair enough, but are they not separate issues?

**Comment by gjb2048** [comment]
BTW in the Readme.md file it does state:

6. I'm not sure of the security vulnerabilities of the script on the server so after you have used it and are confident of the results then move it from the '/course/format/grid/upgrade/' folder to a safe non-served folder.

**Comment by ewallah** [comment]
THX for the changes!
